### ISSUE TITLE
[BVC-108] Large invalid response data causes the app to crash with Out of Memory exception.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-app#1181]
# Summary | Résumé

Application should be robust enough to handle large invalid data from a server, possibly a malicious server (john: or faulty server response on our part). Sending large response data of around 100MB in response to the  GET exposure-configuration request caused the android mobile application to crash with the following message being displayed to the user:

Could Not invoke FileReaderModule.readAsText
null

Failed to allocate a 200000012 byte allocation with 25165824 free bytes and 155MB until OOM, max allowed footprint 130630480, growth limit 268435456

snippet of related logs:
2020-07-07 14:13:08.230 26688-26946/app.covidshield W/app.covidshiel: Throwing OutOfMemoryError "Failed to allocate a 200000012 byte allocation with 25165824 free bytes and 155MB until OOM, max allowed footprint 130630480, growth limit 268435456" (VmSize 4233836 kB)
2020-07-07 14:13:08.310 26688-26946/app.covidshield W/app.covidshiel: Throwing OutOfMemoryError "Failed to allocate a 200000016 byte allocation with 25165824 free bytes and 155MB until OOM, max allowed footprint 130630480, growth limit 268435456" (VmSize 4233836 kB)
2020-07-07 14:13:08.314 26688-26946/app.covidshield E/unknown:ReactNative: Exception in native call
java.lang.RuntimeException: Could not invoke FileReaderModule.readAsText
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:214)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
at android.os.Handler.handleCallback(Handler.java:873) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
at android.os.Looper.loop(Looper.java:214) 
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
at java.lang.Thread.run(Thread.java:764) 
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 200000016 byte allocation with 25165824 free bytes and 155MB until OOM, max allowed footprint 130630480, growth limit 268435456
at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125)
at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
at com.facebook.react.modules.blob.FileReaderModule.readAsText(FileReaderModule.java:62)
at java.lang.reflect.Method.invoke(Native Method) 
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
at android.os.Handler.handleCallback(Handler.java:873) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
at android.os.Looper.loop(Looper.java:214) 
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
at java.lang.Thread.run(Thread.java:764)

**Comment by obrien-j** [comment]
Low priority given the failure path, but will drop in for correctness purposes. This fits into a class of bugs that i'll try to group.

**Comment by craigzour** [comment]
@maxneuvians 's idea is good but do we really want to have such verification mechanism which would require two HTTP calls every time we want to get the configuration? Like I mentioned in #1183 we need to make sure we communicate with the proper backend (DeviceCheck/SafetyNet attestation). cc @timarney

**Comment by timarney** [comment]
Given we're mostly doing maintenance work at this point we won't be implementing any changes for this scenario.
